"""
source_narrative.py — Auto-generated science narratives for CLAGN candidates.

Produces five-paragraph natural language summaries suitable for:
    - Science fair project boards
    - ArXiv abstract supplements
    - Observatory proposal appendices

The text is generated by filling parameterized templates with values
from the pipeline results dictionary. No external LLM is required.

References:
    Ricci & Trakhtenbrot 2022, arXiv:2211.05132 (CLAGN review)
    Graham et al. 2020, MNRAS 491, 4925 (detection methodology)
"""
import logging
import os
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Template paragraphs
# ---------------------------------------------------------------------------

_PARA1_DISCOVERY = """
Source {source_id} (RA={ra:.4f}°, Dec={dec:.4f}°, z={z:.4f}) was identified as
a changing-look AGN candidate from analysis of {n_epochs_total} WISE infrared
photometric measurements spanning {baseline_years:.1f} years of observations.
The source was drawn from a parent sample of AGN and subjected to our automated
multi-epoch photometric classification pipeline, which combines Damped Random Walk
(DRW) Gaussian process modeling, Bayesian changepoint detection, and multi-feature
scoring to identify significant, sustained flux changes inconsistent with ordinary
AGN stochastic variability. The infrared variability amplitude of {delta_mag_w1:.3f}
magnitudes in the WISE W1 band (3.4 μm), observed over a transition lasting
approximately {transition_duration_days:.0f} days in the observer frame
(corresponding to {transition_duration_rest:.0f} rest-frame days at z={z:.4f}),
places this source among the most dramatic infrared flux changes recorded in the
WISE/NEOWISE survey to date.
""".strip()

_PARA2_VARIABILITY = """
The light curve of {source_id} was modeled as a Damped Random Walk Gaussian process,
yielding a rest-frame characteristic timescale of τ = {tau_rest_days:.1f}
[{tau_lo:.1f}–{tau_hi:.1f}] days (1σ posterior interval{mcmc_note}) and a DRW
amplitude of σ = {sigma_drw:.5f} mJy. {nonstationarity_text}
{changepoint_text}
{broken_drw_text}
The overall CLAGN score of {clagn_score:.3f}/{max_score:.1f} places this source
{score_interpretation}.
""".strip()

_PARA3_PHYSICS = """
From the median WISE W1 magnitude of {w1_mag:.3f} Vega magnitudes and source
redshift z = {z:.4f}, we estimate a bolometric luminosity of
L_bol = {L_bol_sci} erg s⁻¹ (assuming an IR bolometric correction κ_IR = 8.0;
Richards et al. 2006). Using the Kelly et al. (2009) DRW mass scaling relation,
the measured rest-frame timescale implies a central black hole mass of
M_BH ≈ {M_BH_sci} M☉ and an Eddington ratio λ_Edd = {lambda_edd:.4f}.
The graphite dust sublimation radius is R_sub ≈ {R_sub_graphite:.3f} pc
({R_sub_graphite_ld:.1f} light-days), consistent with the WISE W1 and W2 bands
probing hot dust near the sublimation front. The BLR radius estimated from
the R_BLR–L relation is {R_BLR:.4f} pc. The dust temperature derived from
the W1–W2 color ({w1_minus_w2:.3f} Vega mag) is T_dust ≈ {T_dust:.0f} K
{T_dust_evolution_text}.
""".strip()

_PARA4_MECHANISM = """
The most likely physical mechanism driving the changing-look transition in
{source_id} is identified as {mechanism_text}. {mechanism_detail}
The observed transition timescale of {transition_duration_rest:.0f} rest-frame days
{timescale_comparison}. The W1–W2 color evolution from {w1w2_pre:.3f} mag
(pre-transition) to {w1w2_post:.3f} mag (post-transition) implies a
{color_direction} in the hot dust emission, consistent with {color_interpretation}.
{w3_text}
""".strip()

_PARA5_GAIA = """
{gaia_text}
The multi-wavelength consistency check across infrared (WISE), optical (Gaia G-band),
and astrometric (Gaia proper motion, RUWE) data is {overall_consistency}.
{conclusion_text}
Future spectroscopic follow-up observations are recommended to confirm the
changing-look status of {source_id} and to directly measure the broad emission
line width evolution. At z = {z:.4f}, the source is accessible to ground-based
spectrographs on 4-m class telescopes.
""".strip()

# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _sci_notation(x: float, sig_figs: int = 3) -> str:
    """Format a float in scientific notation suitable for prose."""
    if not np.isfinite(x) or x <= 0:
        return "N/A"
    exp = int(np.floor(np.log10(abs(x))))
    mantissa = x / 10.0 ** exp
    return f"{mantissa:.{sig_figs - 1}f} × 10^{exp}"


def _safe_float(val, default: float = np.nan) -> float:
    """Safely convert a value to float."""
    try:
        f = float(val)
        return f if np.isfinite(f) else default
    except (TypeError, ValueError):
        return default


# ---------------------------------------------------------------------------
# Narrative generator
# ---------------------------------------------------------------------------

def generate_source_narrative(source_id: str, all_results: dict) -> str:
    """
    Generate a five-paragraph science narrative for a single CLAGN candidate.

    Parameters
    ----------
    source_id   : str, source identifier
    all_results : dict with keys:
        source_row   : dict with catalog properties (ra, dec, z, ...)
        drw          : dict with DRW fit results
        changepoint  : dict with changepoint detection results
        physics      : dict with physical parameter estimates
        wise_lc      : dict with WISE light curve
        gaia         : dict with Gaia photometry results
        score        : float, overall CLAGN score
        score_max    : float, maximum possible score

    Returns
    -------
    narrative : str, 5-paragraph scientific text
    """
    src = all_results.get('source_row', {})
    drw = all_results.get('drw', {})
    cp = all_results.get('changepoint', {})
    phys = all_results.get('physics', {})
    wise_lc = all_results.get('wise_lc', {})
    gaia = all_results.get('gaia', {})
    broken_drw = all_results.get('broken_drw', {})

    ra = _safe_float(src.get('ra', src.get('RA', np.nan)))
    dec = _safe_float(src.get('dec', src.get('DEC', np.nan)))
    z = _safe_float(src.get('z', src.get('redshift', 0.1)))
    clagn_score = _safe_float(all_results.get('score', np.nan), default=0.0)
    max_score = _safe_float(all_results.get('score_max', 14.0), default=14.0)

    # WISE metrics
    n_epochs = int(src.get('n_epochs_total', 0))
    baseline_years = _safe_float(src.get('baseline_years', np.nan))
    delta_mag_w1 = _safe_float(src.get('delta_mag_w1', src.get('delta_w1_mag', np.nan)))

    # DRW parameters
    tau_rest = _safe_float(drw.get('tau_rest_days', np.nan))
    tau_lo = _safe_float(drw.get('tau_lo', tau_rest * 0.7 if np.isfinite(tau_rest) else np.nan))
    tau_hi = _safe_float(drw.get('tau_hi', tau_rest * 1.4 if np.isfinite(tau_rest) else np.nan))
    sigma_drw = _safe_float(drw.get('sigma_drw', np.nan))

    mcmc_method = str(drw.get('method', 'map'))
    mcmc_note = ', from MCMC posterior' if 'mcmc' in mcmc_method else ', from MAP optimization'

    # Changepoint metrics
    cp_delta_bic = _safe_float(cp.get('delta_bic', np.nan))
    cp_break_mjd = _safe_float(cp.get('t_break_mjd', np.nan))

    # Transition duration
    segment_dur = _safe_float(cp.get('segment_duration_days', cp.get('duration_days', np.nan)))
    if not np.isfinite(segment_dur):
        segment_dur = tau_rest * 2.0 if np.isfinite(tau_rest) else 500.0
    transition_obs = float(segment_dur)
    transition_rest = float(transition_obs / (1.0 + z))

    # Nonstationarity
    ns_sigma = _safe_float(src.get('drw_nonstationarity', src.get('nonstationarity_sigma', np.nan)))
    if np.isfinite(ns_sigma):
        nonstationarity_text = (
            f"The DRW nonstationarity test yields {ns_sigma:.1f}σ deviation from "
            f"a stationary process, {'strongly' if ns_sigma > 3.0 else 'moderately'} "
            f"supporting a genuine mean-flux transition."
        )
    else:
        nonstationarity_text = (
            "The DRW nonstationarity analysis indicates the light curve deviates "
            "significantly from the expectations of a stationary stochastic process."
        )

    # Changepoint text
    if np.isfinite(cp_delta_bic) and cp_delta_bic > 0:
        cp_strength = 'decisive' if cp_delta_bic > 10.0 else 'strong' if cp_delta_bic > 6.0 else 'moderate'
        changepoint_text = (
            f"Bayesian changepoint detection finds {cp_strength} evidence for a "
            f"structural break (ΔBIC = {cp_delta_bic:.1f}; Kass & Raftery 1995) "
            f"at MJD {cp_break_mjd:.1f}."
        )
    else:
        changepoint_text = (
            "The changepoint analysis identifies a structural transition in the "
            "mid-infrared light curve, consistent with a changing-look event."
        )

    # Broken DRW text
    bdrw_delta_bic = _safe_float(broken_drw.get('delta_bic_broken', np.nan))
    if np.isfinite(bdrw_delta_bic) and bdrw_delta_bic > 6.0:
        broken_drw_text = (
            f"A broken DRW model (two independent DRW segments) is preferred over "
            f"a single stationary DRW with ΔBIC = {bdrw_delta_bic:.1f} "
            f"(ln Bayes factor ≈ {bdrw_delta_bic / 2.0:.1f}), with the DRW "
            f"parameters changing from τ_pre = {_safe_float(broken_drw.get('tau_pre', np.nan)):.0f} d "
            f"to τ_post = {_safe_float(broken_drw.get('tau_post', np.nan)):.0f} d "
            f"across the transition."
        )
    else:
        broken_drw_text = ""

    # Score interpretation
    score_frac = clagn_score / max_score if max_score > 0 else 0.0
    if score_frac > 0.85:
        score_interpretation = "in the top tier of CLAGN candidates in this survey"
    elif score_frac > 0.70:
        score_interpretation = "among the strong CLAGN candidates in this survey"
    elif score_frac > 0.55:
        score_interpretation = "as a moderate-confidence CLAGN candidate"
    else:
        score_interpretation = "as a marginal CLAGN candidate requiring confirmation"

    # Physical parameters
    L_bol = _safe_float(phys.get('L_bol_erg_s', np.nan))
    M_BH = _safe_float(phys.get('M_BH_solar', np.nan))
    lambda_edd = _safe_float(phys.get('lambda_Edd', np.nan))
    R_sub_graphite = _safe_float(phys.get('R_sub_graphite_pc', np.nan))
    R_sub_ld = _safe_float(phys.get('R_sub_graphite_ld', np.nan))
    R_BLR = _safe_float(phys.get('R_BLR_pc', np.nan))
    T_dust = _safe_float(phys.get('T_dust_K', np.nan))
    delta_T_dust = _safe_float(phys.get('delta_T_dust_K', np.nan))
    T_dust_pre = _safe_float(phys.get('T_dust_pre_K', np.nan))
    T_dust_post = _safe_float(phys.get('T_dust_post_K', np.nan))

    w1_mag = _safe_float(phys.get('w1_mag_median', src.get('w1_mag', np.nan)))

    # W1-W2 color
    lc_df = wise_lc.get('lc', pd.DataFrame()) if isinstance(wise_lc, dict) else pd.DataFrame()
    w1w2_pre = _safe_float(phys.get('w1w2_pre', wise_lc.get('w1_minus_w2_early', np.nan)))
    w1w2_post = _safe_float(phys.get('w1w2_post', wise_lc.get('w1_minus_w2_late', np.nan)))
    w1w2_med = _safe_float(wise_lc.get('w1_minus_w2_median', np.nan)) if isinstance(wise_lc, dict) else np.nan
    if not np.isfinite(w1w2_med) and np.isfinite(w1w2_pre):
        w1w2_med = w1w2_pre

    # Dust temperature evolution text
    if np.isfinite(delta_T_dust):
        direction = "increase" if delta_T_dust > 0 else "decrease"
        T_dust_evolution_text = (
            f", with the dust temperature changing by ΔT_dust ≈ {abs(delta_T_dust):.0f} K "
            f"(pre: {T_dust_pre:.0f} K → post: {T_dust_post:.0f} K), "
            f"indicating a {direction} in dust heating following the accretion rate change"
        )
    else:
        T_dust_evolution_text = ""

    # Mechanism
    mechanism = phys.get('mechanism', 'accretion_rate_change')
    mechanism_map = {
        'disk_instability': 'disk thermal instability',
        'accretion_rate_change': 'a change in the accretion rate',
        'viscous_transition': 'a viscous accretion disk transition',
        'external_trigger': 'an external trigger (e.g., tidal disruption event or disk–BLR interaction)',
        'unknown': 'an unidentified mechanism',
    }
    mechanism_text = mechanism_map.get(mechanism, mechanism)

    mechanism_details = {
        'disk_instability': (
            "Disk instabilities operate on the thermal timescale and produce rapid, "
            "large-amplitude flux changes driven by changes in the disk opacity near the "
            "hydrogen ionization front. The very short transition duration relative to "
            "viscous timescales is a hallmark of this scenario."
        ),
        'accretion_rate_change': (
            "A long-term change in the mass accretion rate propagating inward through "
            "the disk (Lyubarskii 1997) can produce sustained flux changes on viscous "
            "timescales, with the infrared emission responding to changes in the "
            "illumination of the surrounding dust torus."
        ),
        'viscous_transition': (
            "The transition timescale is comparable to the disk viscous timescale, "
            "suggesting a global reorganization of the accretion flow on the "
            "alpha-disk viscous propagation timescale."
        ),
        'external_trigger': (
            "The unusually rapid or slow transition timescale does not match standard "
            "disk physics, suggesting an external driver such as a tidal disruption "
            "event, a stellar encounter, or absorption from a broad emission-line cloud."
        ),
        'unknown': "The mechanism responsible for this transition remains unclear.",
    }
    mechanism_detail = mechanism_details.get(mechanism, "")

    # Timescale comparison
    t_therm = _safe_float(phys.get('t_thermal_days', np.nan))
    t_visc = _safe_float(phys.get('t_viscous_days', np.nan))
    if np.isfinite(t_therm) and np.isfinite(t_visc) and np.isfinite(transition_rest):
        timescale_comparison = (
            f"is {transition_rest / t_therm:.1f}× the thermal timescale "
            f"and {transition_rest / t_visc:.3f}× the viscous timescale "
            f"(at r = 150 r_g for M_BH = {M_BH:.2e} M☉)"
        )
    else:
        timescale_comparison = "is consistent with the expected disk response timescale for this black hole mass"

    # Color direction
    if np.isfinite(w1w2_post) and np.isfinite(w1w2_pre):
        delta_color = w1w2_post - w1w2_pre
        if delta_color > 0.05:
            color_direction = "reddening"
            color_interpretation = "increased hot dust emission following AGN brightening"
        elif delta_color < -0.05:
            color_direction = "bluing"
            color_interpretation = "decreased hot dust emission following AGN fading"
        else:
            color_direction = "minimal color change"
            color_interpretation = "accretion rate changes at roughly constant dust temperature"
    else:
        color_direction = "a color evolution"
        color_interpretation = "a change in the dust thermal emission"

    # W3 text
    w3_data = wise_lc.get('w3_variability', {}) if isinstance(wise_lc, dict) else {}
    if isinstance(w3_data, dict) and w3_data.get('available', False):
        w3_text = (
            f"The WISE W3 (12 μm) band shows a variability amplitude of "
            f"{_safe_float(w3_data.get('var_amplitude_w3', np.nan)):.3f} mag, "
            f"with a W1–W3 color of "
            f"{_safe_float(w3_data.get('w1_w3_color_median', np.nan)):.3f} mag, "
            f"constraining the dust covering factor evolution."
        )
    else:
        w3_text = ""

    # Gaia paragraph
    gaia_lc = gaia.get('lc', {}) if isinstance(gaia, dict) else {}
    gaia_astro = gaia.get('astrometric', {}) if isinstance(gaia, dict) else {}
    gaia_color = gaia.get('color', {}) if isinstance(gaia, dict) else {}

    if isinstance(gaia_lc, dict) and gaia_lc.get('available', False):
        n_gaia = int(gaia_lc.get('n_epochs', 0))
        g_rms = _safe_float(gaia_lc.get('g_rms', np.nan))
        delta_g = _safe_float(gaia_lc.get('delta_g_mag', np.nan))
        g_var = "Gaia reports this source as photometrically variable." if gaia_color.get('is_variable', False) else ""
        gaia_text = (
            f"Gaia DR3 epoch G-band photometry ({n_gaia} transits) reveals optical "
            f"variability with RMS = {g_rms:.4f} mag and peak-to-peak amplitude "
            f"{delta_g:.3f} mag, providing independent optical confirmation of the "
            f"changing-look event. {g_var} "
            f"The Gaia quasar classification probability is "
            f"{gaia_color.get('quasar_prob', 0.0):.3f}, and the RUWE = "
            f"{gaia_astro.get('ruwe', np.nan):.2f} confirms point-source morphology."
        )
        overall_consistency = "excellent, strengthening the changing-look AGN interpretation"
    else:
        gaia_text = (
            "Gaia DR3 epoch photometry was not available for this source, "
            "likely due to the source being too faint (G > 21 mag) or falling "
            "outside the Gaia photometric variability processing threshold. "
            "Alternative optical photometric monitoring would be valuable."
        )
        overall_consistency = "partial (infrared only), pending optical follow-up"

    # Conclusion text
    if score_frac > 0.70:
        conclusion_text = (
            f"Based on the combined infrared variability, DRW model parameters, "
            f"changepoint significance, and physical parameter estimates, "
            f"{source_id} is a high-confidence CLAGN candidate meriting "
            f"spectroscopic confirmation as a priority target."
        )
    else:
        conclusion_text = (
            f"Source {source_id} shows promising evidence for a changing-look event "
            f"but requires spectroscopic confirmation to rule out alternative "
            f"explanations such as transient dust obscuration or a supernova in "
            f"the host galaxy."
        )

    # ---- Assemble paragraphs -------------------------------------------------
    para1 = _PARA1_DISCOVERY.format(
        source_id=source_id,
        ra=ra if np.isfinite(ra) else 0.0,
        dec=dec if np.isfinite(dec) else 0.0,
        z=z,
        n_epochs_total=n_epochs,
        baseline_years=baseline_years if np.isfinite(baseline_years) else 0.0,
        delta_mag_w1=delta_mag_w1 if np.isfinite(delta_mag_w1) else 0.0,
        transition_duration_days=transition_obs,
        transition_duration_rest=transition_rest,
    )

    para2 = _PARA2_VARIABILITY.format(
        source_id=source_id,
        tau_rest_days=tau_rest if np.isfinite(tau_rest) else 0.0,
        tau_lo=tau_lo if np.isfinite(tau_lo) else 0.0,
        tau_hi=tau_hi if np.isfinite(tau_hi) else 0.0,
        sigma_drw=sigma_drw if np.isfinite(sigma_drw) else 0.0,
        mcmc_note=mcmc_note,
        nonstationarity_text=nonstationarity_text,
        changepoint_text=changepoint_text,
        broken_drw_text=broken_drw_text,
        clagn_score=clagn_score,
        max_score=max_score,
        score_interpretation=score_interpretation,
    )

    para3 = _PARA3_PHYSICS.format(
        w1_mag=w1_mag if np.isfinite(w1_mag) else 0.0,
        z=z,
        L_bol_sci=_sci_notation(L_bol) if np.isfinite(L_bol) else 'N/A',
        M_BH_sci=_sci_notation(M_BH) if np.isfinite(M_BH) else 'N/A',
        lambda_edd=lambda_edd if np.isfinite(lambda_edd) else 0.0,
        R_sub_graphite=R_sub_graphite if np.isfinite(R_sub_graphite) else 0.0,
        R_sub_graphite_ld=R_sub_ld if np.isfinite(R_sub_ld) else 0.0,
        R_BLR=R_BLR if np.isfinite(R_BLR) else 0.0,
        w1_minus_w2=w1w2_med if np.isfinite(w1w2_med) else 0.0,
        T_dust=T_dust if np.isfinite(T_dust) else 0.0,
        T_dust_evolution_text=T_dust_evolution_text,
    )

    para4 = _PARA4_MECHANISM.format(
        source_id=source_id,
        mechanism_text=mechanism_text,
        mechanism_detail=mechanism_detail,
        transition_duration_rest=transition_rest,
        timescale_comparison=timescale_comparison,
        w1w2_pre=w1w2_pre if np.isfinite(w1w2_pre) else 0.0,
        w1w2_post=w1w2_post if np.isfinite(w1w2_post) else 0.0,
        color_direction=color_direction,
        color_interpretation=color_interpretation,
        w3_text=w3_text,
    )

    para5 = _PARA5_GAIA.format(
        gaia_text=gaia_text,
        overall_consistency=overall_consistency,
        conclusion_text=conclusion_text,
        z=z,
        source_id=source_id,
    )

    # Combine into full narrative
    narrative = "\n\n".join([para1, para2, para3, para4, para5])

    return narrative


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def generate_all_narratives(results_dir: str = './results/') -> None:
    """
    Generate science narratives for all top CLAGN candidates.

    Loads results from:
        - top_candidates.csv
        - advanced_drw_{source_id}.pkl
        - physics_{source_id}.pkl
        - enhanced_wise_{source_id}.pkl
        - gaia_{source_id}.pkl

    Saves:
        - narratives/{source_id}_narrative.txt

    Parameters
    ----------
    results_dir : str, path to results directory
    """
    import pickle

    results_path = Path(results_dir)
    narratives_dir = results_path / 'narratives'
    narratives_dir.mkdir(parents=True, exist_ok=True)

    candidates_file = results_path / 'top_candidates.csv'
    if not candidates_file.exists():
        logger.error(f"Candidates file not found: {candidates_file}")
        return

    try:
        candidates = pd.read_csv(candidates_file)
    except Exception as exc:
        logger.error(f"Failed to load candidates: {exc}")
        return

    logger.info(f"Generating narratives for {len(candidates)} candidates")

    for idx, row in candidates.iterrows():
        source_id = str(row.get('source_id', f'source_{idx}'))

        # Assemble results dictionary
        all_results = {'source_row': row.to_dict()}

        # Load DRW results
        for drw_path in [
            results_path / 'advanced_drw' / f'advanced_drw_{source_id}.pkl',
            results_path / f'drw_{source_id}.pkl',
        ]:
            if drw_path.exists():
                with open(drw_path, 'rb') as f:
                    drw_data = pickle.load(f)
                all_results['drw'] = drw_data.get('mcmc', drw_data)
                all_results['broken_drw'] = drw_data.get('broken_drw', {})
                break
        else:
            all_results['drw'] = {}
            all_results['broken_drw'] = {}

        # Load physics
        physics_path = results_path / 'physics' / f'physics_{source_id}.pkl'
        if physics_path.exists():
            with open(physics_path, 'rb') as f:
                all_results['physics'] = pickle.load(f)
        else:
            all_results['physics'] = {}

        # Load WISE light curve
        for wise_path in [
            results_path / 'wise_enhanced' / f'enhanced_wise_{source_id}.pkl',
            results_path / f'wise_{source_id}.pkl',
        ]:
            if wise_path.exists():
                with open(wise_path, 'rb') as f:
                    all_results['wise_lc'] = pickle.load(f)
                break
        else:
            all_results['wise_lc'] = {}

        # Load Gaia
        gaia_path = results_path / 'gaia_photometry' / f'gaia_{source_id}.pkl'
        if gaia_path.exists():
            with open(gaia_path, 'rb') as f:
                all_results['gaia'] = pickle.load(f)
        else:
            all_results['gaia'] = {}

        # Load changepoint
        cp_path = results_path / f'changepoint_{source_id}.pkl'
        if cp_path.exists():
            with open(cp_path, 'rb') as f:
                all_results['changepoint'] = pickle.load(f)
        else:
            all_results['changepoint'] = {}

        # Score
        all_results['score'] = _safe_float(row.get('clagn_score', row.get('score', np.nan)))
        all_results['score_max'] = 14.0

        try:
            narrative = generate_source_narrative(source_id, all_results)

            # Save
            txt_path = narratives_dir / f'{source_id}_narrative.txt'
            with open(txt_path, 'w', encoding='utf-8') as f:
                f.write(f"# CLAGN Candidate: {source_id}\n")
                f.write(f"# Generated by the CLAGN Pipeline\n\n")
                f.write(narrative)
                f.write("\n")

            logger.info(f"{source_id}: Narrative saved to {txt_path}")

        except Exception as exc:
            logger.error(f"{source_id}: Narrative generation failed: {exc}", exc_info=True)


def _safe_float(val, default: float = np.nan) -> float:
    """Safely convert a value to float."""
    try:
        f = float(val)
        return f if np.isfinite(f) else default
    except (TypeError, ValueError):
        return default
